Repository IBM/ibm-metering-operator, pull requests merged in 2020-09, with the labels that each got.

#128 update csv to 3.7.1
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.1/ibm-metering-operator.v3.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.1/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.1/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.1/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.1/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.1/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  scripts/bump-up-csv.sh
  scripts/push-images-rh.sh
  scripts/update-operand-tag.sh
  version/version.go
Labels: approved, lgtm, size/XXL

#129 add arch labels to support platforms in catalog
  deploy/olm-catalog/ibm-metering-operator/3.7.1/ibm-metering-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#130 supress unnecessary log messages from metric server
  cmd/manager/main.go
  deploy/olm-catalog/ibm-metering-operator/3.7.1/ibm-metering-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/metering/metering_controller.go
Labels: approved, lgtm, size/M

#131 update image sha to beta1 for content testing
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#132 update checkracm
  pkg/controller/metering/metering_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#133 update ubi image and operand versions to remediate vulnerability
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.7.1/ibm-metering-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/containers.go
Labels: approved, lgtm, size/M

#134 get latest SHA for MCMUI image
  deploy/olm-catalog/ibm-metering-operator/3.7.1/ibm-metering-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#135 update operator sha
  deploy/olm-catalog/ibm-metering-operator/3.7.1/ibm-metering-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#136 use tag instead of SHA for operator image
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.7.1/ibm-metering-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
  scripts/push-images-rh.sh
Labels: approved, lgtm, size/M

#137 create operator version 3.7.2
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.2/ibm-metering-operator.v3.7.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.2/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.2/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.2/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.2/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.2/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  scripts/bump-up-csv.sh
  version/version.go
Labels: approved, lgtm, size/XXL

#138 get SHAs for MCMP update
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.7.2/ibm-metering-operator.v3.7.2.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/containers.go
Labels: approved, lgtm, size/S

#139 fix defect that deleted sender cert
  pkg/controller/metering/metering_controller.go
Labels: approved, lgtm, size/M
