Repository IBM/ibm-metering-operator, pull requests merged in 2020-05, with the labels that each got.

#66 rename meteringreport crd
  deploy/crds/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/role.yaml
  pkg/apis/operator/v1alpha1/meteringreportserver_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_meteringreportserver.go
  pkg/controller/meteringreportserver/meteringreportserver_controller.go
Labels: approved, lgtm, size/L

#67 update csv with meteringreportserver crd
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.0/operator.ibm.com_meteringreportservers_crd.yaml
Labels: approved, lgtm, size/S

#68 add more permissions for metering-report-server
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M

#69 update operator to use latest clean ubi images
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#70 pull operand images by SHA instead of tag
  Makefile
  cmd/manager/main.go
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringreportserver/meteringreportserver_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
  scripts/get-image-sha.sh
Labels: approved, lgtm, size/L

#71 update tls flows between ingress to ui
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#72 remove unnecessary role
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#73 allow deployment to scale to 0
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringreportserver/meteringreportserver_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
Labels: approved, lgtm, size/M

#74 use new cmd to get SHA and change env var names
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/containers.go
  scripts/get-image-sha.sh
Labels: approved, lgtm, size/M

#75 save replica count if it is zero
  pkg/resources/containers.go
  pkg/resources/reconcile.go
Labels: approved, lgtm, size/S

#76 increase resources limits so operator pod can start on Power
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#77 use doc template for CSV and readme
  Makefile
  README.md
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#79 allow metering ui to run without IAM and dynamically detect IAM
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#80 apply ID updates to CSV
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#81 get operand SHAs for GA
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#82 update csv to beta channel
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
Labels: approved, lgtm, size/XS

#83 create operator version 3.6.1
  .osdk-scorecard.yaml
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.1/ibm-metering-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.1/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.1/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.1/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.1/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.1/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/resources/containers.go
  version/version.go
Labels: approved, lgtm, size/XXL

#84 disable admission plugin
  pkg/resources/containers.go
Labels: approved, lgtm, size/XS

#85 update dm version to 3.5.1
  deploy/olm-catalog/ibm-metering-operator/3.6.1/ibm-metering-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/containers.go
Labels: approved, lgtm, size/XS

#86 remove authentication-skip-lookup flag
  pkg/resources/containers.go
Labels: approved, lgtm, size/XS

#87 get SHAs for 361 GA
  deploy/olm-catalog/ibm-metering-operator/3.6.1/ibm-metering-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  scripts/get-image-sha.sh
Labels: approved, lgtm, size/M

#88 update report sha and modify script utilities for mac
  common/scripts/push-csv.sh
  deploy/olm-catalog/ibm-metering-operator/3.6.1/ibm-metering-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  scripts/get-image-sha.sh
Labels: approved, lgtm, size/M

#89 move 3.6.1 to beta channel
  deploy/olm-catalog/ibm-metering-operator/3.6.1/ibm-metering-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
