Repository IBM/ibm-metering-operator, pull requests merged in 2020-06, with the labels that each got.

#90 create operator version 3.6.2
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.2/ibm-metering-operator.v3.6.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.2/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.2/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.2/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.2/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.2/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#91 add cert and env vars for MCM UI
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.6.2/ibm-metering-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#92 move 3.6.2 to the beta channel
  deploy/olm-catalog/ibm-metering-operator/3.6.2/ibm-metering-operator.v3.6.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#93 move 3.6.2 into stable channel
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
Labels: approved, lgtm, size/XS

#95 add 3.6.3 csv
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.3/ibm-metering-operator.v3.6.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.3/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.3/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.3/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.3/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.3/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  pkg/resources/containers.go
  version/version.go
Labels: approved, lgtm, size/XXL

#96 update mcmui image sha
  deploy/olm-catalog/ibm-metering-operator/3.6.3/ibm-metering-operator.v3.6.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#97 move 363 to beta
  deploy/olm-catalog/ibm-metering-operator/3.6.3/ibm-metering-operator.v3.6.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#98 move 363 into stable-v1 channel
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
Labels: approved, lgtm, size/XS
