Repository IBM/ibm-metering-operator, pull requests merged in 2020-01, with the labels that each got.

#2 update owners with additional reviewers and approvers
  OWNERS
Labels: approved, lgtm, size/XS

#6 fix image name for building
  Makefile
Labels: approved, lgtm, size/XS

#7 create certificate for metering API
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/role.yaml
  pkg/apis/addtoscheme_certmanager_v1alpha1.go
  pkg/apis/certmanager/group.go
  pkg/apis/certmanager/v1alpha1/certificate_common.go
  pkg/apis/certmanager/v1alpha1/certificate_types.go
  pkg/apis/certmanager/v1alpha1/doc.go
  pkg/apis/certmanager/v1alpha1/register.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/resources/containers.go
Labels: approved, lgtm, size/XXL

#8 create Ingress for metering API
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  pkg/apis/certmanager/v1alpha1/certificate_common.go
  pkg/apis/operator/v1alpha1/metering_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/resources/containers.go
Labels: approved, lgtm, size/L

#9 fix code coverage.
  CONTRIBUTING.md
  Makefile
  common/scripts/codecov.sh
Labels: approved, lgtm, size/XS
