Repository IBM/ibm-metering-operator, pull requests merged in 2020-03, with the labels that each got.

#31 add info to CSV and change cluster issuer
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  pkg/resources/containers.go
Labels: approved, lgtm, size/S

#32 add metering annotations
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#33 remove svc.cluster.local. change Nodes to Pods in Status
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringuis_crd.yaml
  pkg/apis/operator/v1alpha1/common_spec.go
  pkg/apis/operator/v1alpha1/metering_types.go
  pkg/apis/operator/v1alpha1/meteringmulticloudui_types.go
  pkg/apis/operator/v1alpha1/meteringsender_types.go
  pkg/apis/operator/v1alpha1/meteringui_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#34 use sha for non amd images to properly build arch images
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/S

#35 prep for Red Hat certification
  .osdk-scorecard.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  scripts/create-bundle.sh
Labels: approved, lgtm, size/L

#36 use new values for annotations
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#37 Add clusterhealth.ibm.com/dependencies annotation in pod spec
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#38 update operand images to quay locations
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  pkg/resources/containers.go
Labels: approved, lgtm, size/S

#39 set default status so RH scan will pass
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringuis_crd.yaml
  pkg/apis/operator/v1alpha1/common_spec.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#40 use arch list for nodeAffinity
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
Labels: approved, lgtm, size/M

#41 add certificate CRD to operator
  deploy/crds/certificate-crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/certificate-crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XL

#42 downgrade ingress and node affinity to support k8s 1.11
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#43 add additional role for ingress in extensions
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#44 remove certificate CRD due to conflict
  deploy/crds/certificate-crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/certificate-crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XL

#45 change metering channel to stable-v3
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
Labels: approved, lgtm, size/XS

#46 change metering channel to stable-v1 and use GA version
  README.md
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#47 update external doc url
  README.md
Labels: approved, lgtm, size/XS
