Repository IBM/ibm-metering-operator, pull requests merged in 2020-11, with the labels that each got.

#149 added additional roles required for reports on ocp 4.5 and updated shas
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#150 Sgrube 41740 crdrole
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#151 update image SHA for DM and UI
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#152 update image SHA for UI
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#153 update to latest ubi and metering images
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#154 update shas for power and z
  Makefile
Labels: approved, lgtm, size/XS

#155 updates for ibm certification
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#156 udate to version 3.8.1
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.1/ibm-metering-operator.v3.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.1/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.1/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.1/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.1/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.1/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL
