Repository IBM/ibm-metering-operator, pull requests merged in 2020-02, with the labels that each got.

#12 Added required cluster roles for metering deployments and pass operat…
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/operator.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticlusterui/meteringmulticlusterui_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#13 add controller for metering-sender
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/role.yaml
  pkg/apis/operator/v1alpha1/meteringsender_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_meteringsender.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticlusterui/meteringmulticlusterui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#14 add func to create secret-check and init containers
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticlusterui/meteringmulticlusterui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#15 update entire resource
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticlusterui/meteringmulticlusterui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
Labels: approved, lgtm, size/XL

#16 rename operator as ibm-metering-operator
  build/Dockerfile
  build/bin/entrypoint
  cmd/manager/main.go
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  pkg/apis/addtoscheme_certmanager_v1alpha1.go
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/controller/add_metering.go
  pkg/controller/add_meteringmulticlusterui.go
  pkg/controller/add_meteringsender.go
  pkg/controller/add_meteringui.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticlusterui/meteringmulticlusterui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#18 Sgrube olm
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringmulticlusteruis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
Labels: approved, lgtm, size/XL

#19 add support to push csv to quay
  Makefile
  common/scripts/push-csv.sh
Labels: approved, lgtm, size/M

#20 make metering-receiver optional and rename MeteringMultiClusterUI to …
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/apis/operator/v1alpha1/metering_types.go
  pkg/apis/operator/v1alpha1/meteringmulticloudui_types.go
  pkg/apis/operator/v1alpha1/meteringsender_types.go
  pkg/apis/operator/v1alpha1/meteringui_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_meteringmulticloudui.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XXL

#21 update crs for meta operator onboarding
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#22 use public cert-manager
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/apis/addtoscheme_certmanager_v1alpha1.go
  pkg/apis/certmanager/group.go
  pkg/apis/certmanager/v1alpha1/certificate_common.go
  pkg/apis/certmanager/v1alpha1/certificate_types.go
  pkg/apis/certmanager/v1alpha1/doc.go
  pkg/apis/certmanager/v1alpha1/register.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#23 optimize CRDs
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringuis_crd.yaml
  pkg/apis/operator/v1alpha1/common_spec.go
  pkg/apis/operator/v1alpha1/metering_types.go
  pkg/apis/operator/v1alpha1/meteringmulticloudui_types.go
  pkg/apis/operator/v1alpha1/meteringsender_types.go
  pkg/apis/operator/v1alpha1/meteringui_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#24 add cluster roles to operator role adn rolebinding files
  common/scripts/delete-csv.sh
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/L

#25 only update changed resources. set replica for UI and MCMUI.
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringuis_crd.yaml
  pkg/apis/operator/v1alpha1/meteringmulticloudui_types.go
  pkg/apis/operator/v1alpha1/meteringui_types.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
  version/version.go
Labels: approved, lgtm, size/XXL

#26 change certificate creation logic
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  pkg/controller/metering/metering_controller.go
  pkg/resources/reconcile.go
Labels: approved, lgtm, size/S

#27 Sgrube defaults
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#28 update role names for correct sa role binding
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/XS

#29 get secret names and cluster issuer from CR
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.0/operator.ibm.com_meteringuis_crd.yaml
  pkg/apis/operator/v1alpha1/common_spec.go
  pkg/apis/operator/v1alpha1/metering_types.go
  pkg/apis/operator/v1alpha1/meteringmulticloudui_types.go
  pkg/apis/operator/v1alpha1/meteringui_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL
