Repository IBM/ibm-metering-operator, pull requests merged in 2020-07, with the labels that each got.

#99 new scripts for operator versioning and RH cert
  .osdk-scorecard.yaml
  Makefile
  go.mod
  go.sum
  scripts/bump-up-csv.sh
  scripts/get-image-sha.sh
  scripts/push-images-rh.sh
  scripts/rh-scan/add-certman-info.sh
  scripts/rh-scan/create-bundle.sh
  scripts/update-operand-tag.sh
Labels: approved, size/L

#100 create operator version 3.7.0
  .osdk-scorecard.yaml
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  pkg/resources/containers.go
  version/version.go
Labels: approved, lgtm, size/XXL

#101 add resources and replicas to CRs
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringuis_crd.yaml
  pkg/apis/operator/v1alpha1/common_spec.go
  pkg/apis/operator/v1alpha1/metering_types.go
  pkg/apis/operator/v1alpha1/meteringreportserver_types.go
  pkg/apis/operator/v1alpha1/meteringsender_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringreportserver/meteringreportserver_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#102 add specDescriptors for new fields
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  scripts/bump-up-csv.sh
Labels: approved, lgtm, size/S

#103 set resource limits for multiple workloads
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meterings_crd.yaml
  pkg/apis/operator/v1alpha1/metering_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
Labels: approved, lgtm, size/L

#104 specify iam ns for security middleware package
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#105 update ubi image to remediate VA scans
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/S

#106 update to push to artifactory
  Makefile
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/S

#107 Sgrube 39237 cicd2
  Makefile
Labels: approved, lgtm, size/XS

#108 hard code version
  Makefile
Labels: approved, lgtm, size/XS

#109 use scratch repo for local builds
  Makefile
Labels: approved, lgtm, size/XS
