Repository IBM/ibm-metering-operator, pull requests merged in 2020-08, with the labels that each got.

#110 Remove productVersion metering annotations for 3Q2020
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/utils.go
Labels: lgtm, size/XS

#111 update latest image shas
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#112 update script to get operator SHA
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  scripts/get-image-sha.sh
Labels: approved, lgtm, size/L

#113 update go version for psirt
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
Labels: approved, lgtm, size/S

#114 update shas to latest
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#115 add pod antiaffinity and update shas
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringui/meteringui_controller.go
Labels: approved

#116 update crd status with content certification required versions property
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringuis_crd.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/common_spec.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/controller/meteringreportserver/meteringreportserver_controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/controller/meteringui/meteringui_controller.go
Labels: approved, lgtm, size/L

#120 update csv
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#121 preserve certman labels and other small updates
  Makefile
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/controller/metering/metering_controller.go
  pkg/resources/reconcile.go
Labels: approved, lgtm, size/M

#122 add removal processing for mcm sender related objects for RACM
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/metering/metering_controller.go
Labels: approved, lgtm, size/L

#123 add client to get IngressController
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/metering/metering_controller.go
Labels: approved, lgtm, size/M

#125 make status.versions optional
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/crds/operator.ibm.com_meterings_crd.yaml
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.0/operator.ibm.com_meteringuis_crd.yaml
  pkg/apis/operator/v1alpha1/common_spec.go
Labels: approved, lgtm, size/S

#126 add roles required for routes
  deploy/olm-catalog/ibm-metering-operator/3.7.0/ibm-metering-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M
