Repository IBM/ibm-metering-operator, pull requests merged in 2020-10, with the labels that each got.

#140 bump version to 3.8.0
  .osdk-scorecard.yaml
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.0/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.0/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.0/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.8.0/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#142 create version 3.7.3 and fix default resource limits for report-server
  .osdk-scorecard.yaml
  README.md
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreportserver_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.3/ibm-metering-operator.v3.7.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.3/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.3/operator.ibm.com_meteringreportservers_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.3/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.3/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.7.3/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  pkg/resources/containers.go
  version/version.go
Labels: approved, lgtm, size/XXL

#144 reduce cluster permissions
  deploy/role.yaml
  pkg/resources/containers.go
Labels: approved, lgtm, size/L

#145 use namespace cert issuer
  deploy/role.yaml
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#146 add roles for mcmreader and update csv
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/L

#147 update image shasa
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#148 update image shas
  deploy/olm-catalog/ibm-metering-operator/3.8.0/ibm-metering-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
