Repository IBM/ibm-metering-operator, pull requests merged in 2020-04, with the labels that each got.

#48 Update README.md
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#51 update remaining version refs to 3.6.0
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
  scripts/create-bundle.sh
  version/version.go
Labels: approved, lgtm, size/S

#49 add resources
  go.mod
  go.sum
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/controller/metering/metering_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
Labels: approved, lgtm, ok-to-test, size/L

#52 fix apiservice issue
  pkg/controller/metering/metering_controller.go
  pkg/resources/containers.go
Labels: approved, lgtm, ok-to-test, size/S

#53 add metering hard dependencies
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#54 fix parms and auth for APIservice
  deploy/role.yaml
  pkg/controller/metering/metering_controller.go
Labels: approved, lgtm, size/S

#56 update dm image version to 3.4.1 and operator to 3.5.1
  Makefile
  pkg/resources/containers.go
  version/version.go
Labels: approved, lgtm, size/XS

#57 update operator to use maintenance dm image
  Makefile
  pkg/resources/containers.go
  version/version.go
Labels: approved, lgtm, size/XS

#58 Update operandBindInfo instance
  deploy/olm-catalog/ibm-metering-operator/3.6.0/ibm-metering-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#55 add developers to owners file
  OWNERS
Labels: approved, lgtm, size/XS

#59 Meteringreport crd
  deploy/crds/operator.ibm.com_meteringreports_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringreport_cr.yaml
  pkg/apis/operator/v1alpha1/meteringreport_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_meteringreport.go
  pkg/controller/metering/metering_controller.go
  pkg/controller/meteringreport/meteringreport_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
Labels: approved, lgtm, size/XL

#61 update 3.5 csv to be 3.5.1
  deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.1/ibm-metering-operator.v3.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.1/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.1/operator.ibm.com_meterings_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.1/operator.ibm.com_meteringsenders_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/3.5.1/operator.ibm.com_meteringuis_crd.yaml
  deploy/olm-catalog/ibm-metering-operator/ibm-metering-operator.package.yaml
  deploy/operator.yaml
  scripts/create-bundle.sh
Labels: approved, lgtm, size/XL

#62 add language to fenced block
  README.md
Labels: approved, lgtm, size/M

#63 update to latest ubi minimal image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#64 add more permissions for metering-report
  cmd/manager/main.go
  deploy/crds/operator.ibm.com_meteringreports_crd.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M

#65 update owners file
  OWNERS
Labels: approved, lgtm, size/XS
